### ISSUE TITLE
Question about 2 component communicating

### ISSUE THREAD

**Issue by hshahi** [nigrosimone/ng-portal#1]
Hi,
Thank you for your article and component. I have one question and that is if compA and CompB communicate through your decorator,
if compA instantiate first and its property set, then later on CompB instantiate would compB property receive very last emitted value by compA property?, if not it would make sense use Behaviour subject internally and receiver search for senders and ask for last value.

Thanks
Shahi

**Comment by nigrosimone** [comment]
Hi,
Behind the scenes there Is a rxjs Subject that manage each property connection. I can switch the library to use a Behaviour subject, probably Is more correct!

**Comment by nigrosimone** [comment]
> if compA instantiate first and its property set, then later on CompB instantiate would compB property receive very last emitted value by compA property?

yes! it receive the last emitted value

**Comment by hshahi** [comment]
May I ask a different question, is it possible to have dynamic key, say same control is created in 3 tabs and each have
different data of same type so that each individual compoenent receive their own data based on that key.

 @ngPortalInput({key: data.idString}) inputValue: string;

constructor(data: MyDataType) {
}

MyDataType {
idString: 'uniqueId1', // for differnt data this will be 'uniqueId2'
}

**Comment by nigrosimone** [comment]
Hi @hshahi, yes! but you need to use NgPortalService

Input

```ts
constructor(private data: MyDataType, private ngPortalService: NgPortalService) {
    // send(key, value): Send a "value" for the "key"
    this.ngPortalService.send(data.idString, value: any);
}
```
Output
```ts
constructor(private data: MyDataType, private ngPortalService: NgPortalService) {
    // get(key):  Return an Observable for the "key"
    this.ngPortalService.get(data.idString).subscribe(value => console.log(value));
}
```
